[build]
  publish = "dist"
  command = "npm run build"

# Proxy API requests to your Flask backend
[[redirects]]
  from = "/api/*"
  to = "https://your-flask-backend.herokuapp.com/:splat"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200